// src/components/react_app/AmisEditor.tsx
/*
 * @Author: nbn
 * @Date: 2023-09-07 23:02:35
 * @LastEditors: nbn
 * @LastEditTime: 2023-09-07 23:23:33
 * @FilePath: /amis-widget/src/components/react_app/AmisEditor.tsx
 * @Description:
 */
import { Editor } from "amis-editor";
import "amis/lib/themes/cxd.css";
import "amis/lib/helper.css";
import "amis/sdk/iconfont.css";
import "amis-editor-core/lib/style.css";

import { SchemaObject } from "amis";

interface IProps {
  schema: SchemaObject;
}

export default (props: IProps) => {
  return (
    <Editor
      theme={"cxd"}
      preview={false}
      isMobile={false}
      value={props.schema}
      onChange={() => {}}
      onPreview={() => {
        // store.setPreview(true);
      }}
      onSave={() => {}}
      className="is-fixed"
      // $schemaUrl={schemaUrl}
      showCustomRenderersPanel={true}
      amisEnv={
        {
          // fetcher: store.fetcher,
          // notify: store.notify,
          // alert: store.alert,
          // copy: store.copy
        }
      }
    />
  );
};

// src/components/AmisEditor.vue
<!--
 * @Author: nbn
 * @Date: 2023-09-07 23:15:06
 * @LastEditors: nbn
 * @LastEditTime: 2023-09-07 23:16:29
 * @FilePath: /amis-widget/src/components/AmisEditor.vue
 * @Description: 
-->
<template>
  <AmisRenderReact :schema="schema"></AmisRenderReact>
</template>

<script setup lang="ts">


import { Schema } from 'amis';
import AmisEditor from './react_app/AmisEditor';

import { applyPureReactInVue } from 'veaury'
defineProps<{
  schema?: Schema
}>()


const AmisRenderReact = applyPureReactInVue(AmisEditor)



</script>

<style scoped></style>
